config/routes.rb
Rails.application.routes.draw do
  root 'scrapers#index'
  resources :scrapers, only: :index do
    collection do
      post :scrape
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item
	include ActiveModel::Model
	attr_accessor :name, :modifiers, :price

	def initialize(attributes = {})
		attributes.each do |name, value|
			send("#{name}=", value)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scrapers_controller.rb
class ScrapersController < ApplicationController

  def index
    @items = []
  end

  def scrape
    domain_name = URI.parse(params[:url]).host
    if domain_name == 'www.trycaviar.com'
      @items, @message = ScraperService.scratch(domain_name, params[:url])
    else
      @message = params[:url].blank? ?
        'Please, Fill the url' :
        'Sorry, not serving domain other than www.trycaviar.com'

      render 'scrape_error'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="landing_page">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"></a>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

<script>
  $('#scrape_input').bind('input', function() { 
    $('#error p').text('')
  });

  $("#submit").click(function(){
    $('#items_grid').html("<div class='loader' style='display:inline-block'>")
  });
</script>
  

app/views/scrapers/_error.html.erb
<p style="color: red;text-align:center"><%= @message %></p>

<script>
	$(".loader").remove()
</script>

app/views/scrapers/_items_list.html.erb
<% if items.present? %>
	<table>
		<tr>
			<th>Name</th>
			<th>Modifiers</th>
			<th>Price</th>
		</tr>
		<% items.each do |item| %>
			<tr>
				<td><%= item.name %></td>
				<td><%= item.modifiers.join(',') %></td>
				<td><%= item.price %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	<div style="background-color: white; padding: 10px" class="col-md-offset-4 col-md-4">
		<h3 style="color: red;">Oppps!</h3>
		<p style="color: black; font-weight: bold"><%= @message %><p>
	</div>
<% end %>

<script>
	$(".loader").remove()
</script>

app/views/scrapers/index.html.erb
<div>
  <div class='col-md-12'>
    <header id="landing_header_page" class='col-md-offset-4 col-md-4'>
      <%= form_tag scrape_scrapers_path, :remote => true do %>
        <div class="input-group">
          <%= text_field_tag :url, "", class: 'form-control', id: "scrape_input"%>
          <span class="input-group-btn">
            <%= submit_tag 'Scrape', class:'btn btn-primary', id:'submit'%>
          </span>
        </div>
        <div id="error" style="background-color: white; text-align: center"></div>
      <% end %>
    </header>
  </div>
  <div class="col-md-12" style="margin-top: 100px">
    <div class="card" style="width: 100%;">
      <div class="card-body">
        <div id="items_grid" style="text-align: center">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scrapers/scrape.js.erb
$("#items_grid").html("<%= escape_javascript(render partial: 'items_list', locals: { items: @items } ) %>");

app/views/scrapers/scrape_error.js.erb
$(".loader").remove()
$("#error").html("<%= escape_javascript(render partial: 'error') %>");